#!/usr/sbin/nft -f
flush ruleset
table inet filter {
  chain input {
    type filter hook input priority 0; policy drop;
    ct state established,related accept
    iif lo accept
    ip saddr 10.10.0.0/24 accept
    ip saddr 35.235.240.0/20 tcp dport 22 accept
    drop
  }
  chain forward {
    type filter hook forward priority 0; policy drop;
  }
  chain output {
    type filter hook output priority 0; policy drop;
    ct state established,related accept
    oif lo accept
    ip daddr 10.10.0.0/24 accept
    ip daddr 169.254.169.254 accept
    drop
  }
}
