/// @file fleet_controller.cc
/// @brief Relay-side signed fleet policy puller.

#include "hyper_derp/fleet_controller.h"

#include <arpa/inet.h>
#include <fcntl.h>
#include <netdb.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <unistd.h>

#include <cerrno>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <random>
#include <string>
#include <vector>

#include <openssl/err.h>
#include <openssl/ssl.h>
#include <sodium.h>
#include <spdlog/spdlog.h>

namespace hyper_derp {

namespace {

// -- tiny URL split ----------------------------------

struct ParsedUrl {
  std::string host;
  uint16_t port = 443;
  std::string path;
};

bool ParseHttpsUrl(const std::string& url,
                   ParsedUrl* out) {
  std::string s = url;
  if (s.starts_with("https://")) s = s.substr(8);
  else if (s.starts_with("http://")) return false;
  size_t slash = s.find('/');
  std::string authority = slash == std::string::npos
                              ? s
                              : s.substr(0, slash);
  out->path = slash == std::string::npos
                  ? std::string("/")
                  : s.substr(slash);
  size_t colon = authority.find(':');
  if (colon == std::string::npos) {
    out->host = authority;
  } else {
    out->host = authority.substr(0, colon);
    out->port = static_cast<uint16_t>(
        std::stoi(authority.substr(colon + 1)));
  }
  return !out->host.empty();
}

// -- tiny base64 (decode only; Python sign.py emits
// standard-alphabet base64 without newlines) --------

int B64Val(char c) {
  if (c >= 'A' && c <= 'Z') return c - 'A';
  if (c >= 'a' && c <= 'z') return c - 'a' + 26;
  if (c >= '0' && c <= '9') return c - '0' + 52;
  if (c == '+') return 62;
  if (c == '/') return 63;
  return -1;
}

bool B64Decode(const std::string& in,
               std::vector<uint8_t>* out) {
  out->clear();
  out->reserve((in.size() * 3) / 4);
  int bits = 0;
  int held = 0;
  for (char c : in) {
    if (c == '=') break;
    if (c == '\n' || c == '\r' || c == ' ') continue;
    int v = B64Val(c);
    if (v < 0) return false;
    held = (held << 6) | v;
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      out->push_back(
          static_cast<uint8_t>((held >> bits) & 0xFF));
    }
  }
  return true;
}

// -- very small JSON helpers (string + int extraction)
//
// The bundle is small, schema-tight, and generated by
// our own signer. A minimal hand-rolled scanner keeps
// this file dependency-free.

const char* FindField(const char* s, const char* end,
                      const std::string& key) {
  std::string needle = std::string("\"") + key + "\"";
  const char* p = s;
  while (p + needle.size() <= end) {
    if (std::memcmp(p, needle.data(),
                    needle.size()) == 0) {
      return p + needle.size();
    }
    ++p;
  }
  return nullptr;
}

bool ExtractString(const std::string& json,
                   const std::string& key,
                   std::string* out) {
  const char* e = json.data() + json.size();
  const char* p = FindField(json.data(), e, key);
  if (!p) return false;
  while (p < e && *p != '"') ++p;
  if (p >= e) return false;
  ++p;
  const char* start = p;
  while (p < e && *p != '"') {
    if (*p == '\\' && p + 1 < e) p += 2;
    else ++p;
  }
  if (p >= e) return false;
  out->assign(start, p - start);
  return true;
}

bool ExtractInt(const std::string& json,
                const std::string& key, int64_t* out) {
  const char* e = json.data() + json.size();
  const char* p = FindField(json.data(), e, key);
  if (!p) return false;
  while (p < e &&
         !(*p == '-' || (*p >= '0' && *p <= '9'))) {
    ++p;
  }
  if (p >= e) return false;
  *out = std::strtoll(p, nullptr, 10);
  return true;
}

// -- OpenSSL HTTPS GET -------------------------------

int TcpConnect(const std::string& host, uint16_t port) {
  addrinfo hints{};
  hints.ai_family = AF_UNSPEC;
  hints.ai_socktype = SOCK_STREAM;
  addrinfo* res = nullptr;
  std::string sport = std::to_string(port);
  if (getaddrinfo(host.c_str(), sport.c_str(), &hints,
                  &res) != 0) {
    return -1;
  }
  int fd = -1;
  for (auto* ai = res; ai != nullptr; ai = ai->ai_next) {
    fd = socket(ai->ai_family, ai->ai_socktype,
                ai->ai_protocol);
    if (fd < 0) continue;
    if (connect(fd, ai->ai_addr, ai->ai_addrlen) == 0) {
      break;
    }
    close(fd);
    fd = -1;
  }
  freeaddrinfo(res);
  return fd;
}

struct HttpsResponse {
  int status = 0;
  std::string body;
};

bool HttpsGet(const FleetControllerConfig& cfg,
              const ParsedUrl& url, int64_t since,
              HttpsResponse* out) {
  int fd = TcpConnect(url.host, url.port);
  if (fd < 0) return false;

  SSL_CTX* ctx = SSL_CTX_new(TLS_client_method());
  if (!ctx) {
    close(fd);
    return false;
  }
  SSL_CTX_set_min_proto_version(ctx, TLS1_2_VERSION);
  if (!cfg.ca_bundle.empty()) {
    SSL_CTX_load_verify_locations(ctx,
                                   cfg.ca_bundle.c_str(),
                                   nullptr);
  } else {
    SSL_CTX_set_default_verify_paths(ctx);
  }
  SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER, nullptr);
  if (!cfg.client_cert.empty() &&
      !cfg.client_key.empty()) {
    if (SSL_CTX_use_certificate_file(
            ctx, cfg.client_cert.c_str(),
            SSL_FILETYPE_PEM) != 1 ||
        SSL_CTX_use_PrivateKey_file(
            ctx, cfg.client_key.c_str(),
            SSL_FILETYPE_PEM) != 1) {
      SSL_CTX_free(ctx);
      close(fd);
      return false;
    }
  }

  SSL* ssl = SSL_new(ctx);
  SSL_set_fd(ssl, fd);
  SSL_set_tlsext_host_name(ssl, url.host.c_str());
  if (SSL_connect(ssl) != 1) {
    SSL_free(ssl);
    SSL_CTX_free(ctx);
    close(fd);
    return false;
  }

  std::string req = "GET " + url.path;
  if (since > 0) {
    req += "?since=" + std::to_string(since);
  }
  req += " HTTP/1.1\r\nHost: " + url.host +
         "\r\nConnection: close\r\nUser-Agent: "
         "hyper-derp/fleet-controller\r\n\r\n";
  if (SSL_write(ssl, req.data(),
                static_cast<int>(req.size())) <= 0) {
    SSL_free(ssl);
    SSL_CTX_free(ctx);
    close(fd);
    return false;
  }

  std::string raw;
  raw.reserve(16 * 1024);
  char buf[4096];
  while (true) {
    int n = SSL_read(ssl, buf, sizeof(buf));
    if (n <= 0) break;
    raw.append(buf, n);
    if (raw.size() > 4 * 1024 * 1024) break;
  }
  SSL_shutdown(ssl);
  SSL_free(ssl);
  SSL_CTX_free(ctx);
  close(fd);

  // Parse HTTP/1.1 response headers (very minimal).
  size_t header_end = raw.find("\r\n\r\n");
  if (header_end == std::string::npos) return false;
  size_t line_end = raw.find("\r\n");
  if (line_end == std::string::npos) return false;
  std::string status_line = raw.substr(0, line_end);
  auto sp1 = status_line.find(' ');
  auto sp2 = status_line.find(' ', sp1 + 1);
  if (sp1 == std::string::npos ||
      sp2 == std::string::npos) {
    return false;
  }
  out->status = std::stoi(
      status_line.substr(sp1 + 1, sp2 - sp1 - 1));
  out->body = raw.substr(header_end + 4);
  return true;
}

bool WriteCache(const std::string& path,
                const std::string& body) {
  if (path.empty()) return true;
  std::string tmp = path + ".tmp";
  FILE* f = std::fopen(tmp.c_str(), "wb");
  if (!f) return false;
  std::fwrite(body.data(), 1, body.size(), f);
  std::fflush(f);
  fsync(fileno(f));
  std::fclose(f);
  if (std::rename(tmp.c_str(), path.c_str()) != 0) {
    std::remove(tmp.c_str());
    return false;
  }
  return true;
}

bool ReadCache(const std::string& path,
               std::string* out) {
  if (path.empty()) return false;
  FILE* f = std::fopen(path.c_str(), "rb");
  if (!f) return false;
  char buf[4096];
  out->clear();
  while (size_t n = std::fread(buf, 1, sizeof(buf), f)) {
    out->append(buf, n);
  }
  std::fclose(f);
  return !out->empty();
}

// -- Inner-payload application -----------------------

HdIntent ParseIntentName(const std::string& s) {
  if (s == "require_direct")
    return HdIntent::kRequireDirect;
  if (s == "prefer_relay") return HdIntent::kPreferRelay;
  if (s == "require_relay")
    return HdIntent::kRequireRelay;
  return HdIntent::kPreferDirect;
}

// Apply parsed inner JSON to the registry.
FleetApplyStatus ApplyInner(FleetController* fc,
                            const std::string& inner) {
  HdFleetPolicy fleet;
  HdFederationPolicy fed =
      fc->hd_peers->federation_policy;

  // Re-parse only the flat bool fields; anything richer
  // can arrive in a future bundle revision without
  // breaking this puller.
  auto take_bool = [&](const std::string& key,
                       bool* dst) {
    auto idx = inner.find("\"" + key + "\"");
    if (idx == std::string::npos) return;
    auto colon = inner.find(':', idx);
    if (colon == std::string::npos) return;
    size_t p = colon + 1;
    while (p < inner.size() &&
           (inner[p] == ' ' || inner[p] == '\t')) {
      ++p;
    }
    if (inner.compare(p, 4, "true") == 0) *dst = true;
    else if (inner.compare(p, 5, "false") == 0)
      *dst = false;
  };
  take_bool("allow_direct", &fleet.allow_direct);
  take_bool("allow_relayed", &fleet.allow_relayed);
  take_bool("require_relay_for_cross_region",
            &fleet.require_relay_for_cross_region);

  {
    std::lock_guard lock(fc->hd_peers->mutex);
    fc->hd_peers->fleet_policy = fleet;
    // Federation updates from the bundle land on the
    // next pull; we leave accept_from alone for now
    // (future bundle schema revision).
    (void)fed;
  }
  return FleetApplyStatus::kOk;
}

bool ApplyRevocations(FleetController* fc,
                      const std::string& inner) {
  uint16_t self_id =
      fc->hd_peers ? fc->hd_peers->relay_id : 0;
  auto idx = inner.find("\"revocations\"");
  if (idx == std::string::npos) return false;
  std::string tail = inner.substr(idx);

  // Peer fingerprint list. Simple scan: every
  // `"peer_fingerprint":"ck_..."` occurrence is a
  // revocation.
  std::vector<std::string> peers;
  size_t pos = 0;
  const std::string kNeedle = "\"peer_fingerprint\"";
  while ((pos = tail.find(kNeedle, pos)) !=
         std::string::npos) {
    size_t colon = tail.find(':', pos);
    if (colon == std::string::npos) break;
    size_t q1 = tail.find('"', colon);
    if (q1 == std::string::npos) break;
    size_t q2 = tail.find('"', q1 + 1);
    if (q2 == std::string::npos) break;
    peers.push_back(tail.substr(q1 + 1, q2 - q1 - 1));
    pos = q2 + 1;
  }
  if (!peers.empty()) {
    std::lock_guard lk(fc->revoked_mu);
    fc->revoked_peers = std::move(peers);
  }

  // Self-revocation: find `"relay_id"` entries and
  // match the numeric value against this relay's id.
  if (self_id == 0) return false;
  auto self_str =
      std::string("\"relay_id\":") +
      std::to_string(self_id);
  auto self_str_sp =
      std::string("\"relay_id\": ") +
      std::to_string(self_id);
  if (tail.find(self_str) != std::string::npos ||
      tail.find(self_str_sp) != std::string::npos) {
    return true;
  }
  return false;
}

}  // namespace

FleetApplyStatus FleetControllerApplyBundle(
    FleetController* fc, const uint8_t* body,
    int body_len) {
  std::string outer(reinterpret_cast<const char*>(body),
                    body_len);
  std::string signed_b64, sig_b64, outer_fleet;
  int64_t outer_version = 0;
  if (!ExtractString(outer, "signed_body_b64",
                     &signed_b64) ||
      !ExtractString(outer, "signature_b64", &sig_b64) ||
      !ExtractString(outer, "fleet_id", &outer_fleet) ||
      !ExtractInt(outer, "version", &outer_version)) {
    return FleetApplyStatus::kParseError;
  }
  if (outer_fleet != fc->config.fleet_id) {
    return FleetApplyStatus::kFleetMismatch;
  }
  if (outer_version <=
      fc->applied_version.load(
          std::memory_order_acquire)) {
    return FleetApplyStatus::kStaleVersion;
  }
  std::vector<uint8_t> signed_bytes, sig;
  if (!B64Decode(signed_b64, &signed_bytes) ||
      !B64Decode(sig_b64, &sig)) {
    return FleetApplyStatus::kParseError;
  }
  std::vector<uint8_t> pk;
  if (!B64Decode(fc->config.signing_pubkey_b64, &pk) ||
      pk.size() !=
          crypto_sign_ed25519_PUBLICKEYBYTES) {
    return FleetApplyStatus::kBadSignature;
  }
  if (sig.size() != crypto_sign_ed25519_BYTES) {
    return FleetApplyStatus::kBadSignature;
  }
  if (crypto_sign_ed25519_verify_detached(
          sig.data(), signed_bytes.data(),
          signed_bytes.size(), pk.data()) != 0) {
    return FleetApplyStatus::kBadSignature;
  }

  std::string inner(
      reinterpret_cast<const char*>(signed_bytes.data()),
      signed_bytes.size());

  // Inner fleet_id + version must match the outer
  // fields (envelope integrity check).
  std::string inner_fleet;
  int64_t inner_version = 0;
  if (!ExtractString(inner, "fleet_id", &inner_fleet) ||
      !ExtractInt(inner, "version", &inner_version) ||
      inner_fleet != outer_fleet ||
      inner_version != outer_version) {
    return FleetApplyStatus::kParseError;
  }

  FleetApplyStatus s = ApplyInner(fc, inner);
  if (s != FleetApplyStatus::kOk) return s;

  if (ApplyRevocations(fc, inner)) {
    fc->self_revoked.store(true,
                           std::memory_order_release);
    fc->applied_version.store(
        inner_version, std::memory_order_release);
    return FleetApplyStatus::kRevoked;
  }

  fc->applied_version.store(inner_version,
                            std::memory_order_release);
  return FleetApplyStatus::kOk;
}

namespace {

void RunLoop(FleetController* fc) {
  std::mt19937 rng{static_cast<uint32_t>(
      std::chrono::steady_clock::now()
          .time_since_epoch()
          .count())};
  std::uniform_int_distribution<int> jitter(-10, 10);
  ParsedUrl url;
  std::string full = fc->config.url;
  if (!full.empty() && full.back() == '/') {
    full.pop_back();
  }
  full += "/api/v1/policy";
  if (!ParseHttpsUrl(full, &url)) {
    spdlog::error(
        "fleet controller: bad url '{}' — disabling",
        fc->config.url);
    return;
  }

  while (fc->running.load(std::memory_order_acquire)) {
    HttpsResponse resp;
    int64_t since = fc->applied_version.load(
        std::memory_order_acquire);
    if (HttpsGet(fc->config, url, since, &resp)) {
      if (resp.status == 304) {
        fc->last_status.store(FleetApplyStatus::kOk,
                              std::memory_order_relaxed);
      } else if (resp.status == 200) {
        auto st = FleetControllerApplyBundle(
            fc,
            reinterpret_cast<const uint8_t*>(
                resp.body.data()),
            static_cast<int>(resp.body.size()));
        fc->last_status.store(st,
                              std::memory_order_relaxed);
        if (st == FleetApplyStatus::kOk ||
            st == FleetApplyStatus::kRevoked) {
          WriteCache(fc->config.bundle_cache_path,
                     resp.body);
        }
        if (st == FleetApplyStatus::kRevoked) {
          spdlog::error(
              "fleet: this relay's id is revoked — "
              "self-terminating");
          // Signal to the main server loop via the
          // self_revoked flag; the loop checks every
          // iteration.
        }
      } else {
        fc->last_status.store(
            FleetApplyStatus::kNetworkError,
            std::memory_order_relaxed);
      }
    } else {
      fc->last_status.store(
          FleetApplyStatus::kNetworkError,
          std::memory_order_relaxed);
    }

    int sleep_s = fc->config.poll_interval_secs +
                  jitter(rng);
    if (sleep_s < 10) sleep_s = 10;
    for (int i = 0; i < sleep_s * 10 &&
                    fc->running.load(
                        std::memory_order_acquire);
         i++) {
      usleep(100000);
    }
  }
}

}  // namespace

bool FleetControllerStart(FleetController* fc,
                          HdPeerRegistry* hd_peers,
                          const FleetControllerConfig&
                              config) {
  fc->config = config;
  fc->hd_peers = hd_peers;
  // Load last-known-good if present so the relay has
  // fleet state even before the first poll succeeds.
  std::string cached;
  if (!config.bundle_cache_path.empty() &&
      ReadCache(config.bundle_cache_path, &cached)) {
    auto st = FleetControllerApplyBundle(
        fc,
        reinterpret_cast<const uint8_t*>(cached.data()),
        static_cast<int>(cached.size()));
    if (st != FleetApplyStatus::kOk &&
        st != FleetApplyStatus::kRevoked) {
      spdlog::warn(
          "fleet: cached bundle apply failed ({})",
          static_cast<int>(st));
    }
  }
  fc->running.store(1, std::memory_order_release);
  fc->thread = std::thread(RunLoop, fc);
  return true;
}

void FleetControllerStop(FleetController* fc) {
  fc->running.store(0, std::memory_order_release);
  if (fc->thread.joinable()) fc->thread.join();
}

void FleetControllerGetRevokedPeers(
    const FleetController* fc,
    std::vector<std::string>* out) {
  std::lock_guard lk(fc->revoked_mu);
  *out = fc->revoked_peers;
}

}  // namespace hyper_derp
